#!/usr/bin/env bash

sed -i -r "s/HOST/${APP_DOMAIN}/g" /etc/nginx/sites-available/default

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# $# Stores the number of command-line arguments that were passed to the shell program.
if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
